apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journiv-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/client-max-body-size: "0"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: journiv.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journiv-service
                port:
                  number: 80
  tls:
    - hosts:
        - journiv.example.com
      secretName: journiv-tls